-- Historial y memoria supervisada del Agente Abdi.
create table if not exists public.agent_conversations (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  conversation_id text not null,
  business_key text not null default 'abdismart',
  user_message text not null,
  assistant_message text not null,
  intent text not null default 'general',
  capture_contact boolean not null default false
);

create index if not exists agent_conversations_created_at_idx
  on public.agent_conversations (created_at desc);
create index if not exists agent_conversations_conversation_id_idx
  on public.agent_conversations (conversation_id);

alter table public.agent_conversations enable row level security;
drop policy if exists "usuarios autenticados leen conversaciones" on public.agent_conversations;
create policy "usuarios autenticados leen conversaciones"
  on public.agent_conversations for select
  to authenticated
  using (true);

comment on table public.agent_conversations is
  'Mensajes del agente web. La escritura ocurre únicamente desde el Worker con service role.';

create table if not exists public.agent_learning_candidates (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  business_key text not null default 'abdismart',
  conversation_id text not null,
  discovery_stage text not null default 'problema',
  user_message text not null,
  assistant_message text not null,
  status text not null default 'pendiente' check (status in ('pendiente','aprobada','descartada')),
  reviewed_at timestamptz,
  reviewed_by uuid
);

create index if not exists agent_learning_candidates_status_idx
  on public.agent_learning_candidates (status, created_at desc);

alter table public.agent_learning_candidates enable row level security;
drop policy if exists "usuarios autenticados revisan aprendizaje" on public.agent_learning_candidates;
create policy "usuarios autenticados revisan aprendizaje"
  on public.agent_learning_candidates for select
  to authenticated
  using (true);
drop policy if exists "usuarios autenticados actualizan aprendizaje" on public.agent_learning_candidates;
create policy "usuarios autenticados actualizan aprendizaje"
  on public.agent_learning_candidates for update
  to authenticated
  using (true)
  with check (true);

create table if not exists public.agent_knowledge (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  business_key text not null default 'abdismart',
  title text not null,
  content text not null,
  source_conversation_id text,
  created_by uuid,
  status text not null default 'approved' check (status in ('approved','archived'))
);

create index if not exists agent_knowledge_business_idx
  on public.agent_knowledge (business_key, status, created_at desc);

alter table public.agent_knowledge enable row level security;
drop policy if exists "usuarios autenticados leen memoria aprobada" on public.agent_knowledge;
create policy "usuarios autenticados leen memoria aprobada"
  on public.agent_knowledge for select
  to authenticated
  using (true);
drop policy if exists "usuarios autenticados gestionan memoria aprobada" on public.agent_knowledge;
create policy "usuarios autenticados gestionan memoria aprobada"
  on public.agent_knowledge for insert
  to authenticated
  with check (true);
drop policy if exists "usuarios autenticados archivan memoria" on public.agent_knowledge;
create policy "usuarios autenticados archivan memoria"
  on public.agent_knowledge for update
  to authenticated
  using (true)
  with check (true);
