-- Analítica y control de consumo para “Imagina tu web con Abdi”.
-- Ejecutar en Supabase antes de habilitar el generador en producción.

create table if not exists public.preview_generations (
  id uuid primary key,
  created_at timestamptz not null default now(),
  actor_hash text not null,
  session_id text not null,
  specialty text,
  input_data jsonb not null default '{}'::jsonb,
  output_data jsonb not null default '{}'::jsonb,
  input_tokens integer not null default 0,
  output_tokens integer not null default 0,
  estimated_cost_usd numeric(12,6) not null default 0,
  status text not null check (status in ('generated', 'fallback', 'error')),
  error_message text
);

create index if not exists preview_generations_actor_day_idx
  on public.preview_generations (actor_hash, created_at desc);

create index if not exists preview_generations_session_idx
  on public.preview_generations (session_id, created_at desc);

create table if not exists public.preview_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  preview_id uuid,
  session_id text,
  event_name text not null check (event_name in (
    'preview_started', 'preview_generated', 'preview_saved',
    'preview_to_brief', 'preview_failed'
  )),
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists preview_events_name_created_idx
  on public.preview_events (event_name, created_at desc);

alter table public.preview_generations enable row level security;
alter table public.preview_events enable row level security;

-- No se crean políticas para anon: estas tablas solo se escriben y consultan
-- desde el Worker mediante SUPABASE_SERVICE_ROLE_KEY.

comment on table public.preview_generations is
  'Generaciones, tokens y costo estimado del constructor Imagina tu web.';

comment on table public.preview_events is
  'Embudo de conversión del constructor Imagina tu web.';
