-- Canal de WhatsApp del agente Abdi (Cloud API de Meta).
--
-- A diferencia del widget web, donde el navegador conserva el historial, en
-- WhatsApp el estado tiene que vivir en el servidor: Meta solo entrega el mensaje
-- nuevo. Por eso aquí sí se guarda una ventana corta de la conversación.

create table if not exists public.whatsapp_conversations (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  business_key text not null default 'abdismart',
  -- Número en formato internacional sin el signo +, tal como lo entrega Meta.
  wa_id text not null,
  profile_name text,
  -- 'humano' detiene al agente para que una persona tome el chat desde el CRM.
  status text not null default 'activa' check (status in ('activa','humano','opted_out')),
  handoff_ready boolean not null default false,
  lead_id bigint,
  known_name text,
  business_type text,
  specialty text,
  problem_detected text,
  impact text,
  current_process text,
  recommended_service text,
  discovery_stage text not null default 'nombre',
  turn_count integer not null default 0,
  -- Últimos 14 turnos como [{role, content}]. El Worker recorta antes de guardar.
  history jsonb not null default '[]'::jsonb,
  last_inbound_at timestamptz,
  last_outbound_at timestamptz,
  unique (business_key, wa_id)
);

create index if not exists whatsapp_conversations_status_idx
  on public.whatsapp_conversations (status, updated_at desc);

create index if not exists whatsapp_conversations_handoff_idx
  on public.whatsapp_conversations (handoff_ready, updated_at desc);

create index if not exists whatsapp_conversations_lead_idx
  on public.whatsapp_conversations (lead_id);

-- Meta reintenta la entrega de un evento si el webhook tarda o falla. Reservar el
-- wamid antes de procesar evita que un reintento produzca una segunda respuesta.
create table if not exists public.whatsapp_events (
  wamid text primary key,
  created_at timestamptz not null default now()
);

create index if not exists whatsapp_events_created_idx
  on public.whatsapp_events (created_at);

alter table public.whatsapp_conversations enable row level security;
alter table public.whatsapp_events enable row level security;

-- El Worker escribe con la service role key, que ignora RLS. Estas políticas son
-- solo para el tablero del CRM.
drop policy if exists "usuarios autenticados leen conversaciones whatsapp" on public.whatsapp_conversations;
create policy "usuarios autenticados leen conversaciones whatsapp"
  on public.whatsapp_conversations for select
  to authenticated
  using (true);

drop policy if exists "usuarios autenticados gestionan conversaciones whatsapp" on public.whatsapp_conversations;
create policy "usuarios autenticados gestionan conversaciones whatsapp"
  on public.whatsapp_conversations for update
  to authenticated
  using (true)
  with check (true);

-- Retención: el historial solo sirve para dar continuidad a la conversación.
-- Ejecutar periódicamente para no acumular texto de conversaciones inactivas.
create or replace function public.whatsapp_purge_old_data(p_days integer default 90)
returns void
language sql
security definer
set search_path = public
as $$
  update public.whatsapp_conversations
     set history = '[]'::jsonb
   where updated_at < now() - make_interval(days => p_days)
     and history <> '[]'::jsonb;

  delete from public.whatsapp_events
   where created_at < now() - interval '7 days';
$$;
